# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: epooja
  pool: 5
  username: hp
  password: #ichigo$

test:
  adapter: postgresql
  encoding: unicode
  database: epooja
  pool: 5
  username: hp
  password: #ichigo$
